### ISSUE TITLE
Feature Request: authentication element

### ISSUE THREAD

**Issue by alexkolson** [byu-oit-appdev/byu-polymer-theme#8]
Would love to have a `<byu-auth>` element that would display a sign in button if not authenticated or your profile picture if you were. It could also handle cas authentication, oauth, etc if we wanted it to.

Not a must-have for me but something I'd like to see. I'd be happy to work on it as I get some time.

**Comment by ThatJoeMoore** [comment]
I'm aiming for MR-4 for this one.  See http://byu-oit-appdev.github.io/byu-polymer-theme/ for the features that I'm planning on adding, but that aren't there yet.

**Comment by ThatJoeMoore** [comment]
Here's my proposal for the markup structure:
```
<byu-login-button current-user-name="Joe Student">
    <byu-cas-login callback-url="https://myservice.byu.edu/cas-callback"></byu-cas-login>
    <byu-oauth-login oauth-url="https://identity-manager.byu.edu" scopes=""></byu-oauth-login>
    <byu-custom-login login-url="https://myservice.byu.edu/my-login"></byu-custom-login>

    <byu-user-menu signout-url="https://myservice.byu.edu/logout">
        <byu-nav-link>My App Account</byu-nav-link>
        <byu-nav-link>My Other App-specific Link</byu-nav-link>
    </byu-user-menu>
</byu-login-button>
```

Where only one of byu-cas-login, byu-oauth-login, or byu-custom-login would be allowed.

If no current-user-name is supplied, we assume that the user is not logged in and we display the sign in button.  Tapping the sign in button will invoke the proper login method.

The byu-user-menu element allows us to customize the dropdown menu that is displayed when a user is logged in.  It will add these links at the top of the menu, in addition to our standard set of links and a sign out link. We will also include an option to disable the default menu items and only display a sign out link.

**Comment by alexkolson** [comment]
:+1:

**Comment by ThatJoeMoore** [comment]
I've now got the CAS implementation working.  It will redirect to CAS, but still doesn't show anything different if you're logged in (and showing your actual login info will require server-side support).

I know that there is some real interest in this issue (esp from @alexkolson and @mhailstone ), so I'll keep you updated on progress.  You can preview it at any time by using

```
bower install --save byu-oit-appdev/byu-polymer-theme#byu-auth
```

That will check things out from the byu-auth branch of the repo.

**Comment by ThatJoeMoore** [comment]
Initial OAuth support has been pushed out.  I've also started work on an element that will be more automatic in its OAuth support.  The default byu-login-oauth element will leave a lot to the consumer so as to not make any wrong assumptions about how things should be processed, but the consumer has to handle the OAuth token response as well as refreshing the token.

The new element, byu-login-oauth-auto, will automatically save any user-specified current state (such as routing information) to the browser's session storage (or to a cookie, if session storage is not available) before redirecting the user to the OAuth server (this also serves as a form of CSRF protection).  It will intercept the page load when the user comes back from the login and re-load the persisted state.  It will also schedule a refresh of the token (if necessary).

**Comment by ThatJoeMoore** [comment]
Completion of this is being delayed to Milestone 5 due to server-side issues with our OAuth implementation.  Once those are ironed out, we'll be able to release this.

**Comment by ThatJoeMoore** [comment]
Closing as obsolete - authentication is now implemented with [byu-authentication](github.com/byu-oit-appdev/polymer-authentication) and [byu-wabs-integration](github.com/byu-oit-appdev/polymer-wabs-integration).
